### ISSUE TITLE
Update ARA XML

### ISSUE THREAD

**Issue by gunnarx** [GENIVI/franca_ara_integration#5]
@ChristopherSchwager 
The ARXML files were added a long time ago.  Since we made changes to the FIDL interface, is it possible that they are out of date?  If possible, could you add a commit with the ARXML that are matching the latest interface? 
Just add to any branch (or create a PR).  I can reorganize it into the right place.
Or maybe @TorstenGoerg @kbirken has these files?

**Comment by ChristopherSchwager** [comment]
Those modifed ARXMLs are available in the following pull request: https://github.com/GENIVI/franca_ara_integration/pull/6

**Comment by gunnarx** [comment]
#6 has been merged a long time ago, so no need to keep this issue open.
